// AUTO-GENERATED FILE. DO NOT EDIT.
// Generated by scripts/build-manifest.mjs from public/photos/*/manifest.json.
// Re-run via `npm run manifest` (also runs on predev/prebuild).

export type PhotoText = {
  position: { x: string; y: string };
  align: "left" | "center" | "right";
  color: string;
};

export type Photo = {
  slug: string;
  filename: string;
  src: string;
  title: string;
  caption: string;
  category: string;
  date: string;
  featured: boolean;
  text: PhotoText;
  section: "hero" | "featured" | "gallery" | "closing";
  order: number;
};

export const heroPhotos: Photo[] = [
  {
    "slug": "konti-hero-image",
    "filename": "konti-hero-image.jpg",
    "src": "/photos/hero/konti-hero-image.jpg",
    "title": "konti",
    "caption": "A cinematic archive of quiet chaos, soft paws, and royal attitude.",
    "category": "Portrait",
    "date": "2026",
    "featured": false,
    "text": {
      "position": {
        "x": "8%",
        "y": "75%"
      },
      "align": "left",
      "color": "#f2f2f2"
    },
    "section": "hero",
    "order": 0
  }
];

export const featuredPhotos: Photo[] = [
  {
    "slug": "konti-nap-architecture",
    "filename": "konti-nap-architecture.jpg",
    "src": "/photos/featured/konti-nap-architecture.jpg",
    "title": "Nap Architecture",
    "caption": "A study in stillness, softness, and complete ownership of the sofa.",
    "category": "Sleep",
    "date": "2026",
    "featured": true,
    "text": {
      "position": {
        "x": "8%",
        "y": "82%"
      },
      "align": "left",
      "color": "#f2f2f2"
    },
    "section": "featured",
    "order": 0
  },
  {
    "slug": "konti-sleep-image",
    "filename": "konti-sleep-image.jpg",
    "src": "/photos/featured/konti-sleep-image.jpg",
    "title": "Dream Paws",
    "caption": "Soft sleep, paws raised in surrender to the afternoon.",
    "category": "Sleep",
    "date": "2026",
    "featured": true,
    "text": {
      "position": {
        "x": "8%",
        "y": "82%"
      },
      "align": "left",
      "color": "#f2f2f2"
    },
    "section": "featured",
    "order": 1
  },
  {
    "slug": "neon-throne-1",
    "filename": "neon-throne-1.jpg",
    "src": "/photos/featured/neon-throne-1.jpg",
    "title": "Neon Throne",
    "caption": "Holding court under quiet purple light.",
    "category": "Portrait",
    "date": "2026",
    "featured": true,
    "text": {
      "position": {
        "x": "8%",
        "y": "82%"
      },
      "align": "left",
      "color": "#f2f2f2"
    },
    "section": "featured",
    "order": 2
  },
  {
    "slug": "upside-down-face",
    "filename": "upside-down-face.jpg",
    "src": "/photos/featured/upside-down-face.jpg",
    "title": "Curious Inversion",
    "caption": "Studying the human from upside down, as one does.",
    "category": "Mood",
    "date": "2026",
    "featured": true,
    "text": {
      "position": {
        "x": "8%",
        "y": "82%"
      },
      "align": "left",
      "color": "#f2f2f2"
    },
    "section": "featured",
    "order": 3
  }
];

export const galleryPhotos: Photo[] = [
  {
    "slug": "alert-on-couch",
    "filename": "alert-on-couch.jpg",
    "src": "/photos/gallery/alert-on-couch.jpg",
    "title": "Alert on the Couch",
    "caption": "Loafed, but listening.",
    "category": "Mood",
    "date": "2026",
    "featured": false,
    "text": {
      "position": {
        "x": "8%",
        "y": "82%"
      },
      "align": "left",
      "color": "#f2f2f2"
    },
    "section": "gallery",
    "order": 0
  },
  {
    "slug": "belly-up-couch",
    "filename": "belly-up-couch.jpg",
    "src": "/photos/gallery/belly-up-couch.jpg",
    "title": "Nap Architecture",
    "caption": "Complete surrender to the cushion.",
    "category": "Sleep",
    "date": "2026",
    "featured": false,
    "text": {
      "position": {
        "x": "8%",
        "y": "82%"
      },
      "align": "left",
      "color": "#f2f2f2"
    },
    "section": "gallery",
    "order": 1
  },
  {
    "slug": "big-eyes-macro-2",
    "filename": "big-eyes-macro-2.jpg",
    "src": "/photos/gallery/big-eyes-macro-2.jpg",
    "title": "Wide Eyes II",
    "caption": "Same look, fewer pixels of distance.",
    "category": "Macro",
    "date": "2026",
    "featured": false,
    "text": {
      "position": {
        "x": "8%",
        "y": "82%"
      },
      "align": "left",
      "color": "#f2f2f2"
    },
    "section": "gallery",
    "order": 2
  },
  {
    "slug": "big-eyes-macro",
    "filename": "big-eyes-macro.jpg",
    "src": "/photos/gallery/big-eyes-macro.jpg",
    "title": "Wide Eyes",
    "caption": "Two big green-gold lenses, observing.",
    "category": "Macro",
    "date": "2026",
    "featured": false,
    "text": {
      "position": {
        "x": "8%",
        "y": "82%"
      },
      "align": "left",
      "color": "#f2f2f2"
    },
    "section": "gallery",
    "order": 3
  },
  {
    "slug": "bw-corner-alert",
    "filename": "bw-corner-alert.jpg",
    "src": "/photos/gallery/bw-corner-alert.jpg",
    "title": "Black & White Alert",
    "caption": "Eyes lit, ears up, body still.",
    "category": "Portrait",
    "date": "2026",
    "featured": false,
    "text": {
      "position": {
        "x": "8%",
        "y": "82%"
      },
      "align": "left",
      "color": "#f2f2f2"
    },
    "section": "gallery",
    "order": 4
  },
  {
    "slug": "bw-overhead-flop",
    "filename": "bw-overhead-flop.jpg",
    "src": "/photos/gallery/bw-overhead-flop.jpg",
    "title": "Overhead Flop",
    "caption": "Looking up, mid-flop.",
    "category": "Mood",
    "date": "2026",
    "featured": false,
    "text": {
      "position": {
        "x": "8%",
        "y": "82%"
      },
      "align": "left",
      "color": "#f2f2f2"
    },
    "section": "gallery",
    "order": 5
  },
  {
    "slug": "bw-paw-study",
    "filename": "bw-paw-study.jpg",
    "src": "/photos/gallery/bw-paw-study.jpg",
    "title": "Paw Study",
    "caption": "Crossed paws, considered gaze.",
    "category": "Portrait",
    "date": "2026",
    "featured": false,
    "text": {
      "position": {
        "x": "8%",
        "y": "82%"
      },
      "align": "left",
      "color": "#f2f2f2"
    },
    "section": "gallery",
    "order": 6
  },
  {
    "slug": "bw-wedged-cushions",
    "filename": "bw-wedged-cushions.jpg",
    "src": "/photos/gallery/bw-wedged-cushions.jpg",
    "title": "Wedged",
    "caption": "Body folded into the gap between cushions.",
    "category": "Sleep",
    "date": "2026",
    "featured": false,
    "text": {
      "position": {
        "x": "8%",
        "y": "82%"
      },
      "align": "left",
      "color": "#f2f2f2"
    },
    "section": "gallery",
    "order": 7
  },
  {
    "slug": "chasing-red-dot-2",
    "filename": "chasing-red-dot-2.jpg",
    "src": "/photos/gallery/chasing-red-dot-2.jpg",
    "title": "Red Dot II",
    "caption": "Eyes still on the prize.",
    "category": "Action",
    "date": "2026",
    "featured": false,
    "text": {
      "position": {
        "x": "8%",
        "y": "82%"
      },
      "align": "left",
      "color": "#f2f2f2"
    },
    "section": "gallery",
    "order": 8
  },
  {
    "slug": "chasing-red-dot",
    "filename": "chasing-red-dot.jpg",
    "src": "/photos/gallery/chasing-red-dot.jpg",
    "title": "Red Dot",
    "caption": "Locked on. The dot does not stand a chance.",
    "category": "Action",
    "date": "2026",
    "featured": false,
    "text": {
      "position": {
        "x": "8%",
        "y": "82%"
      },
      "align": "left",
      "color": "#f2f2f2"
    },
    "section": "gallery",
    "order": 9
  },
  {
    "slug": "corner-loaf-bw",
    "filename": "corner-loaf-bw.jpg",
    "src": "/photos/gallery/corner-loaf-bw.jpg",
    "title": "Corner Loaf · Mono",
    "caption": "Same corner, no color.",
    "category": "Sleep",
    "date": "2026",
    "featured": false,
    "text": {
      "position": {
        "x": "8%",
        "y": "82%"
      },
      "align": "left",
      "color": "#f2f2f2"
    },
    "section": "gallery",
    "order": 10
  },
  {
    "slug": "corner-loaf-sepia-2",
    "filename": "corner-loaf-sepia-2.jpg",
    "src": "/photos/gallery/corner-loaf-sepia-2.jpg",
    "title": "Corner Loaf II",
    "caption": "Eyes half-open. Still in charge.",
    "category": "Sleep",
    "date": "2026",
    "featured": false,
    "text": {
      "position": {
        "x": "8%",
        "y": "82%"
      },
      "align": "left",
      "color": "#f2f2f2"
    },
    "section": "gallery",
    "order": 11
  },
  {
    "slug": "corner-loaf-sepia-3",
    "filename": "corner-loaf-sepia-3.jpg",
    "src": "/photos/gallery/corner-loaf-sepia-3.jpg",
    "title": "Corner Loaf III",
    "caption": "A long stare from the warm corner.",
    "category": "Sleep",
    "date": "2026",
    "featured": false,
    "text": {
      "position": {
        "x": "8%",
        "y": "82%"
      },
      "align": "left",
      "color": "#f2f2f2"
    },
    "section": "gallery",
    "order": 12
  },
  {
    "slug": "corner-loaf-sepia",
    "filename": "corner-loaf-sepia.jpg",
    "src": "/photos/gallery/corner-loaf-sepia.jpg",
    "title": "Corner Loaf",
    "caption": "Wedged into the couch corner like he owns the lease.",
    "category": "Sleep",
    "date": "2026",
    "featured": false,
    "text": {
      "position": {
        "x": "8%",
        "y": "82%"
      },
      "align": "left",
      "color": "#f2f2f2"
    },
    "section": "gallery",
    "order": 13
  },
  {
    "slug": "cradle-paws-bw",
    "filename": "cradle-paws-bw.jpg",
    "src": "/photos/gallery/cradle-paws-bw.jpg",
    "title": "Cradle Paws",
    "caption": "",
    "category": "Sleep",
    "date": "2026",
    "featured": false,
    "text": {
      "position": {
        "x": "8%",
        "y": "82%"
      },
      "align": "left",
      "color": "#f2f2f2"
    },
    "section": "gallery",
    "order": 14
  },
  {
    "slug": "curled-asleep-bw",
    "filename": "curled-asleep-bw.jpg",
    "src": "/photos/gallery/curled-asleep-bw.jpg",
    "title": "Curled",
    "caption": "Folded into himself, completely gone.",
    "category": "Sleep",
    "date": "2026",
    "featured": false,
    "text": {
      "position": {
        "x": "8%",
        "y": "82%"
      },
      "align": "left",
      "color": "#f2f2f2"
    },
    "section": "gallery",
    "order": 15
  },
  {
    "slug": "downward-glance",
    "filename": "downward-glance.jpg",
    "src": "/photos/gallery/downward-glance.jpg",
    "title": "Downward Glance",
    "caption": "Studying the floor like it owes him money.",
    "category": "Mood",
    "date": "2026",
    "featured": false,
    "text": {
      "position": {
        "x": "8%",
        "y": "82%"
      },
      "align": "left",
      "color": "#f2f2f2"
    },
    "section": "gallery",
    "order": 16
  },
  {
    "slug": "electric-blue-alert",
    "filename": "electric-blue-alert.jpg",
    "src": "/photos/gallery/electric-blue-alert.jpg",
    "title": "Electric Blue · Alert",
    "caption": "",
    "category": "Neon",
    "date": "2026",
    "featured": false,
    "text": {
      "position": {
        "x": "8%",
        "y": "82%"
      },
      "align": "left",
      "color": "#f2f2f2"
    },
    "section": "gallery",
    "order": 17
  },
  {
    "slug": "electric-blue-loaf",
    "filename": "electric-blue-loaf.jpg",
    "src": "/photos/gallery/electric-blue-loaf.jpg",
    "title": "Electric Blue · Loaf",
    "caption": "",
    "category": "Neon",
    "date": "2026",
    "featured": false,
    "text": {
      "position": {
        "x": "8%",
        "y": "82%"
      },
      "align": "left",
      "color": "#f2f2f2"
    },
    "section": "gallery",
    "order": 18
  },
  {
    "slug": "electric-blue-portrait",
    "filename": "electric-blue-portrait.jpg",
    "src": "/photos/gallery/electric-blue-portrait.jpg",
    "title": "Electric Blue",
    "caption": "Sat in pure blue light, calmly aware.",
    "category": "Neon",
    "date": "2026",
    "featured": false,
    "text": {
      "position": {
        "x": "8%",
        "y": "82%"
      },
      "align": "left",
      "color": "#f2f2f2"
    },
    "section": "gallery",
    "order": 19
  },
  {
    "slug": "electric-blue-sit",
    "filename": "electric-blue-sit.jpg",
    "src": "/photos/gallery/electric-blue-sit.jpg",
    "title": "Electric Blue · Sit",
    "caption": "",
    "category": "Neon",
    "date": "2026",
    "featured": false,
    "text": {
      "position": {
        "x": "8%",
        "y": "82%"
      },
      "align": "left",
      "color": "#f2f2f2"
    },
    "section": "gallery",
    "order": 20
  },
  {
    "slug": "electric-blue-stare",
    "filename": "electric-blue-stare.jpg",
    "src": "/photos/gallery/electric-blue-stare.jpg",
    "title": "Electric Blue · Stare",
    "caption": "",
    "category": "Neon",
    "date": "2026",
    "featured": false,
    "text": {
      "position": {
        "x": "8%",
        "y": "82%"
      },
      "align": "left",
      "color": "#f2f2f2"
    },
    "section": "gallery",
    "order": 21
  },
  {
    "slug": "eye-macro-side",
    "filename": "eye-macro-side.jpg",
    "src": "/photos/gallery/eye-macro-side.jpg",
    "title": "Macro · Eye",
    "caption": "An eye, in detail. Whiskers like glass thread.",
    "category": "Macro",
    "date": "2026",
    "featured": false,
    "text": {
      "position": {
        "x": "8%",
        "y": "82%"
      },
      "align": "left",
      "color": "#f2f2f2"
    },
    "section": "gallery",
    "order": 22
  },
  {
    "slug": "future-billionaire-note",
    "filename": "future-billionaire-note.jpg",
    "src": "/photos/gallery/future-billionaire-note.jpg",
    "title": "Future Billionaire",
    "caption": "Posing beside a small note of ambition.",
    "category": "Window",
    "date": "2026",
    "featured": false,
    "text": {
      "position": {
        "x": "8%",
        "y": "82%"
      },
      "align": "left",
      "color": "#f2f2f2"
    },
    "section": "gallery",
    "order": 23
  },
  {
    "slug": "golden-eyes-stare",
    "filename": "golden-eyes-stare.jpg",
    "src": "/photos/gallery/golden-eyes-stare.jpg",
    "title": "Golden Eyes",
    "caption": "A direct, unhurried look.",
    "category": "Portrait",
    "date": "2026",
    "featured": false,
    "text": {
      "position": {
        "x": "8%",
        "y": "82%"
      },
      "align": "left",
      "color": "#f2f2f2"
    },
    "section": "gallery",
    "order": 24
  },
  {
    "slug": "looking-skyward",
    "filename": "looking-skyward.jpg",
    "src": "/photos/gallery/looking-skyward.jpg",
    "title": "Looking Skyward",
    "caption": "A bird, probably. Or nothing at all.",
    "category": "Window",
    "date": "2026",
    "featured": false,
    "text": {
      "position": {
        "x": "8%",
        "y": "82%"
      },
      "align": "left",
      "color": "#f2f2f2"
    },
    "section": "gallery",
    "order": 25
  },
  {
    "slug": "neon-throne-1",
    "filename": "neon-throne-1.jpg",
    "src": "/photos/gallery/neon-throne-1.jpg",
    "title": "Neon Throne I",
    "caption": "Purple light, hammock chair, total composure.",
    "category": "Neon",
    "date": "2026",
    "featured": false,
    "text": {
      "position": {
        "x": "8%",
        "y": "82%"
      },
      "align": "left",
      "color": "#f2f2f2"
    },
    "section": "gallery",
    "order": 26
  },
  {
    "slug": "neon-throne-2",
    "filename": "neon-throne-2.jpg",
    "src": "/photos/gallery/neon-throne-2.jpg",
    "title": "Neon Throne II",
    "caption": "",
    "category": "Neon",
    "date": "2026",
    "featured": false,
    "text": {
      "position": {
        "x": "8%",
        "y": "82%"
      },
      "align": "left",
      "color": "#f2f2f2"
    },
    "section": "gallery",
    "order": 27
  },
  {
    "slug": "neon-throne-3",
    "filename": "neon-throne-3.jpg",
    "src": "/photos/gallery/neon-throne-3.jpg",
    "title": "Neon Throne III",
    "caption": "",
    "category": "Neon",
    "date": "2026",
    "featured": false,
    "text": {
      "position": {
        "x": "8%",
        "y": "82%"
      },
      "align": "left",
      "color": "#f2f2f2"
    },
    "section": "gallery",
    "order": 28
  },
  {
    "slug": "neon-throne-4",
    "filename": "neon-throne-4.jpg",
    "src": "/photos/gallery/neon-throne-4.jpg",
    "title": "Neon Throne IV",
    "caption": "",
    "category": "Neon",
    "date": "2026",
    "featured": false,
    "text": {
      "position": {
        "x": "8%",
        "y": "82%"
      },
      "align": "left",
      "color": "#f2f2f2"
    },
    "section": "gallery",
    "order": 29
  },
  {
    "slug": "neon-throne-5",
    "filename": "neon-throne-5.jpg",
    "src": "/photos/gallery/neon-throne-5.jpg",
    "title": "Neon Throne V",
    "caption": "",
    "category": "Neon",
    "date": "2026",
    "featured": false,
    "text": {
      "position": {
        "x": "8%",
        "y": "82%"
      },
      "align": "left",
      "color": "#f2f2f2"
    },
    "section": "gallery",
    "order": 30
  },
  {
    "slug": "neon-throne-6",
    "filename": "neon-throne-6.jpg",
    "src": "/photos/gallery/neon-throne-6.jpg",
    "title": "Neon Throne VI",
    "caption": "",
    "category": "Neon",
    "date": "2026",
    "featured": false,
    "text": {
      "position": {
        "x": "8%",
        "y": "82%"
      },
      "align": "left",
      "color": "#f2f2f2"
    },
    "section": "gallery",
    "order": 31
  },
  {
    "slug": "neon-throne-7",
    "filename": "neon-throne-7.jpg",
    "src": "/photos/gallery/neon-throne-7.jpg",
    "title": "Neon Throne VII",
    "caption": "",
    "category": "Neon",
    "date": "2026",
    "featured": false,
    "text": {
      "position": {
        "x": "8%",
        "y": "82%"
      },
      "align": "left",
      "color": "#f2f2f2"
    },
    "section": "gallery",
    "order": 32
  },
  {
    "slug": "neon-throne-8",
    "filename": "neon-throne-8.jpg",
    "src": "/photos/gallery/neon-throne-8.jpg",
    "title": "Neon Throne VIII",
    "caption": "",
    "category": "Neon",
    "date": "2026",
    "featured": false,
    "text": {
      "position": {
        "x": "8%",
        "y": "82%"
      },
      "align": "left",
      "color": "#f2f2f2"
    },
    "section": "gallery",
    "order": 33
  },
  {
    "slug": "neon-throne-9",
    "filename": "neon-throne-9.jpg",
    "src": "/photos/gallery/neon-throne-9.jpg",
    "title": "Neon Throne IX",
    "caption": "",
    "category": "Neon",
    "date": "2026",
    "featured": false,
    "text": {
      "position": {
        "x": "8%",
        "y": "82%"
      },
      "align": "left",
      "color": "#f2f2f2"
    },
    "section": "gallery",
    "order": 34
  },
  {
    "slug": "paws-up-dream-bw",
    "filename": "paws-up-dream-bw.jpg",
    "src": "/photos/gallery/paws-up-dream-bw.jpg",
    "title": "Dream Paws · Mono",
    "caption": "",
    "category": "Sleep",
    "date": "2026",
    "featured": false,
    "text": {
      "position": {
        "x": "8%",
        "y": "82%"
      },
      "align": "left",
      "color": "#f2f2f2"
    },
    "section": "gallery",
    "order": 35
  },
  {
    "slug": "paws-up-dream",
    "filename": "paws-up-dream.jpg",
    "src": "/photos/gallery/paws-up-dream.jpg",
    "title": "Dream Paws",
    "caption": "Asleep with paws in surrender.",
    "category": "Sleep",
    "date": "2026",
    "featured": false,
    "text": {
      "position": {
        "x": "8%",
        "y": "82%"
      },
      "align": "left",
      "color": "#f2f2f2"
    },
    "section": "gallery",
    "order": 36
  },
  {
    "slug": "peeking-from-corner-2",
    "filename": "peeking-from-corner-2.jpg",
    "src": "/photos/gallery/peeking-from-corner-2.jpg",
    "title": "Corner Peek II",
    "caption": "Still watching.",
    "category": "Mood",
    "date": "2026",
    "featured": false,
    "text": {
      "position": {
        "x": "8%",
        "y": "82%"
      },
      "align": "left",
      "color": "#f2f2f2"
    },
    "section": "gallery",
    "order": 37
  },
  {
    "slug": "peeking-from-corner",
    "filename": "peeking-from-corner.jpg",
    "src": "/photos/gallery/peeking-from-corner.jpg",
    "title": "Corner Peek",
    "caption": "A face appears from the edge of the frame.",
    "category": "Mood",
    "date": "2026",
    "featured": false,
    "text": {
      "position": {
        "x": "8%",
        "y": "82%"
      },
      "align": "left",
      "color": "#f2f2f2"
    },
    "section": "gallery",
    "order": 38
  },
  {
    "slug": "purple-room-collar",
    "filename": "purple-room-collar.jpg",
    "src": "/photos/gallery/purple-room-collar.jpg",
    "title": "Purple Room",
    "caption": "Collar on. Quiet kingdom.",
    "category": "Neon",
    "date": "2026",
    "featured": false,
    "text": {
      "position": {
        "x": "8%",
        "y": "82%"
      },
      "align": "left",
      "color": "#f2f2f2"
    },
    "section": "gallery",
    "order": 39
  },
  {
    "slug": "regal-side-profile",
    "filename": "regal-side-profile.jpg",
    "src": "/photos/gallery/regal-side-profile.jpg",
    "title": "Throne Room",
    "caption": "A long, soft side profile in flat morning light.",
    "category": "Portrait",
    "date": "2026",
    "featured": false,
    "text": {
      "position": {
        "x": "8%",
        "y": "82%"
      },
      "align": "left",
      "color": "#f2f2f2"
    },
    "section": "gallery",
    "order": 40
  },
  {
    "slug": "side-eye-portrait",
    "filename": "side-eye-portrait.jpg",
    "src": "/photos/gallery/side-eye-portrait.jpg",
    "title": "Side Eye",
    "caption": "Verdict already passed.",
    "category": "Mood",
    "date": "2026",
    "featured": false,
    "text": {
      "position": {
        "x": "8%",
        "y": "82%"
      },
      "align": "left",
      "color": "#f2f2f2"
    },
    "section": "gallery",
    "order": 41
  },
  {
    "slug": "sleepy-smile-bw",
    "filename": "sleepy-smile-bw.jpg",
    "src": "/photos/gallery/sleepy-smile-bw.jpg",
    "title": "Sleepy Smile · Mono",
    "caption": "",
    "category": "Sleep",
    "date": "2026",
    "featured": false,
    "text": {
      "position": {
        "x": "8%",
        "y": "82%"
      },
      "align": "left",
      "color": "#f2f2f2"
    },
    "section": "gallery",
    "order": 42
  },
  {
    "slug": "sleepy-smile",
    "filename": "sleepy-smile.jpg",
    "src": "/photos/gallery/sleepy-smile.jpg",
    "title": "Sleepy Smile",
    "caption": "Eyes shut, tiny smile, perfect peace.",
    "category": "Sleep",
    "date": "2026",
    "featured": false,
    "text": {
      "position": {
        "x": "8%",
        "y": "82%"
      },
      "align": "left",
      "color": "#f2f2f2"
    },
    "section": "gallery",
    "order": 43
  },
  {
    "slug": "sunglasses-cat",
    "filename": "sunglasses-cat.png",
    "src": "/photos/gallery/sunglasses-cat.png",
    "title": "Cool Cat",
    "caption": "Shades on. Approval pending.",
    "category": "Portrait",
    "date": "2026",
    "featured": false,
    "text": {
      "position": {
        "x": "8%",
        "y": "82%"
      },
      "align": "left",
      "color": "#f2f2f2"
    },
    "section": "gallery",
    "order": 44
  },
  {
    "slug": "tall-watch-window",
    "filename": "tall-watch-window.jpg",
    "src": "/photos/gallery/tall-watch-window.jpg",
    "title": "Tall Watch",
    "caption": "Eye on something only he can see.",
    "category": "Window",
    "date": "2026",
    "featured": false,
    "text": {
      "position": {
        "x": "8%",
        "y": "82%"
      },
      "align": "left",
      "color": "#f2f2f2"
    },
    "section": "gallery",
    "order": 45
  },
  {
    "slug": "upside-down-face",
    "filename": "upside-down-face.jpg",
    "src": "/photos/gallery/upside-down-face.jpg",
    "title": "Curious Inversion",
    "caption": "From below — ears, whiskers, world flipped.",
    "category": "Mood",
    "date": "2026",
    "featured": false,
    "text": {
      "position": {
        "x": "8%",
        "y": "82%"
      },
      "align": "left",
      "color": "#f2f2f2"
    },
    "section": "gallery",
    "order": 46
  },
  {
    "slug": "window-glance-back",
    "filename": "window-glance-back.jpg",
    "src": "/photos/gallery/window-glance-back.jpg",
    "title": "Glance Back",
    "caption": "Caught mid-thought, looking back.",
    "category": "Window",
    "date": "2026",
    "featured": false,
    "text": {
      "position": {
        "x": "8%",
        "y": "82%"
      },
      "align": "left",
      "color": "#f2f2f2"
    },
    "section": "gallery",
    "order": 47
  },
  {
    "slug": "window-profile-silhouette",
    "filename": "window-profile-silhouette.jpg",
    "src": "/photos/gallery/window-profile-silhouette.jpg",
    "title": "Quiet Sill",
    "caption": "Backlit and still.",
    "category": "Window",
    "date": "2026",
    "featured": false,
    "text": {
      "position": {
        "x": "8%",
        "y": "82%"
      },
      "align": "left",
      "color": "#f2f2f2"
    },
    "section": "gallery",
    "order": 48
  },
  {
    "slug": "window-stretch-silhouette",
    "filename": "window-stretch-silhouette.jpg",
    "src": "/photos/gallery/window-stretch-silhouette.jpg",
    "title": "Window Stretch",
    "caption": "Reaching toward the world through bars.",
    "category": "Window",
    "date": "2026",
    "featured": false,
    "text": {
      "position": {
        "x": "8%",
        "y": "82%"
      },
      "align": "left",
      "color": "#f2f2f2"
    },
    "section": "gallery",
    "order": 49
  },
  {
    "slug": "window-watcher-kitten",
    "filename": "window-watcher-kitten.jpg",
    "src": "/photos/gallery/window-watcher-kitten.jpg",
    "title": "Window Watcher",
    "caption": "Watching the world move while refusing to participate.",
    "category": "Window",
    "date": "2026",
    "featured": false,
    "text": {
      "position": {
        "x": "8%",
        "y": "82%"
      },
      "align": "left",
      "color": "#f2f2f2"
    },
    "section": "gallery",
    "order": 50
  },
  {
    "slug": "windowsill-profile",
    "filename": "windowsill-profile.jpg",
    "src": "/photos/gallery/windowsill-profile.jpg",
    "title": "Windowsill Profile",
    "caption": "Soft silhouette, blurred trees.",
    "category": "Window",
    "date": "2026",
    "featured": false,
    "text": {
      "position": {
        "x": "8%",
        "y": "82%"
      },
      "align": "left",
      "color": "#f2f2f2"
    },
    "section": "gallery",
    "order": 51
  },
  {
    "slug": "yawn-closeup",
    "filename": "yawn-closeup.jpg",
    "src": "/photos/gallery/yawn-closeup.jpg",
    "title": "The Yawn",
    "caption": "Tongue, fangs, total disregard.",
    "category": "Macro",
    "date": "2026",
    "featured": false,
    "text": {
      "position": {
        "x": "8%",
        "y": "82%"
      },
      "align": "left",
      "color": "#f2f2f2"
    },
    "section": "gallery",
    "order": 52
  }
];

export const closingPhotos: Photo[] = [
  {
    "slug": "window-watcher-kitten",
    "filename": "window-watcher-kitten.jpg",
    "src": "/photos/closing/window-watcher-kitten.jpg",
    "title": "Every ordinary day, archived beautifully.",
    "caption": "",
    "category": "",
    "date": "2026",
    "featured": false,
    "text": {
      "position": {
        "x": "50%",
        "y": "50%"
      },
      "align": "center",
      "color": "#f2f2f2"
    },
    "section": "closing",
    "order": 0
  }
];

export const allPhotos: Photo[] = [
  ...heroPhotos,
  ...featuredPhotos,
  ...galleryPhotos,
  ...closingPhotos,
];

export function findPhotoBySlug(slug: string): Photo | undefined {
  return allPhotos.find((p) => p.slug === slug);
}
